
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: oidc
  annotations:
    kubernetes.io/ingress.class: "kong"
  labels:
    global: "false"
disabled: false # optionally disable the plugin in Kong
plugin: oidc
config: # configuration for the plugin
  client_id: kong-oidc 
  client_secret: xxxxxxxx  # Generated on keyCloak
  realm: kong
  discovery: https://keycloak.localhost/auth/realms/kong-oidc/.well-known/openid-configuration
  scope: openid
  redirect_after_logout_uri : https://keycloak.localhost/auth/realms/kong-oidc/protocol/openid-connect/logout?redirect_uri=https://localhost
---
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: cors
  annotations:
    kubernetes.io/ingress.class: "kong"
  labels:
    global: "true"    
disabled: false # optionally disable the plugin in Kong
plugin: cors
config: 
  origins: 
    - "*"
  credentials: true
  max_age: 3600
  exposed_headers : 
    - "X-Auth-Token"
  preflight_continue: false
---
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: request-transformer
  annotations:
    kubernetes.io/ingress.class: "kong"
  labels:
    global: "false"
disabled: false # optionally disable the plugin in Kong
plugin: request-transformer
config:
  remove:
    headers:
    - cookie
    - x-id-token

